---
title: "DATASOC "
author: "Dirección de Investigación y Publicaciones -- FACSO"
lang: es
date: 2025-10-03
date-format: "MMMM, YYYY"
format:
  # pptx:
  #   reference-doc: template.pptx
  revealjs: 
    footer: "DIP -- FACSO"
    logo: https://raw.githubusercontent.com/facso-investigacion/presentaciones/refs/heads/main/consejo-postgrado/imagenes/logo-dip.jpg
    theme: simple
    css: estilos/custom-facso.css
    slide-number: true
    transition: fade
scrollable: true
---

## Contexto

Para lograr posicionarse como un centro de generación de conocimiento basado en investigación social de relevancia nacional e internacional, la Facultad enfrentá los siguientes desafíos:

1) Falencias en las implementación de una gobernanza de datos efectiva

2) Carencia de canales claros que faciliten sistemáticamente la transferencia del conocimiento hacia la sociedad civil y los tomadores de decisiones

3) Poca preparación institucional para nuevos desafíso científicos y tecnológicos, tales como la inteligencia artificial, el machine learning, la big data y el procesamiento de lenguaje natural. 

## DATASOC

**DATASOC** es una iniciativa de Ciencia de Datos de la Facultad de Ciencias Sociales que busca **posicionar a la Facultad como un referente nacional en el desarrollo y uso estratégico de los datos sociales**, articulando investigación, formación, gestión e impacto. Su quehacer se orienta por **altos estándares de calidad y por los principios de la ciencia abierta**, provimiendo prácticas transparentes y reproducibles en el tratamiento de la información científica. 

Par ello, DATASOC impulsa las siguientes líneas de acción: 

1) Investigación

2) Formación

3) Gobernanza de Datos

4) Apoyo, Impacto y Transferencia

5) Aseguramiento y certificación de Calidad de Datos Sociales

## 1. Investigación

Objetivo: **Consolidar a FACSO como un nodo para el desarrollo de la investigación metodológica y metacientífica avanzada**

Posibles líneas de investigación:

a) Ciencias Sociales computacionales

b) Ciencia Abierta, metaciencia y bibliometría

c) Estudios sobre Instituciones de Educación Superior. 

## 2. Formación 

Objetivo: **Establecer un espacio clave en la formación de estudiantes, académicos y público general**

a) Coordinar, en sinergia con la creación del Colegio Doctoral, a académicos responsables de cursos metodológicos y de análisis de datos

b) Dar espacio para integrar estudiantes de pre y postgrado como pasantes, prácticantes o tesistas

c) Crear una oferta de cursos de extensión orientados al público externo

## 3. Gobernanza de Datos

Objetivo: **Asumir un rol activo en el desarrollo y transferencia de modelos de gobernzanza de datos a la gestión universitaria**

- Desarrollo de [CINDAI](https://dip-facso.shinyapps.io/datos-abiertos-CINDAI/#inicio){target="_blank} en la Dirección de Investigación

- Ofrecer asesoría a otras unidades de la Facultad interesadas en fortalecer la gestión de sus datos internos o desarrollar plataformas de visualización. 

## 4. Asesoría, Impacto y Transferencia

Objetivo: **Ofrecer servicios especializados de acompañamiento técnico a lo largo del ciclo completo de investigación, promoviendo la contribución efectiva al debate público, el diseño de políticas públicas y la toma de decisiones basada en evidencia**

Las áreas de apoyo incluyen:

- Diseño de estudios
- Acceso y uso de datos secundarios
- Procesamiento y análisis reproducible de datos sociales
- Gestión, archivo y apertura de datos. 

## 5. Aseguramiento y certificación de Calidad de Datos Sociales

Objetivo: **Implementar el primer sistema formal de aseguramiento y certificación de calidad de datos científico-sociales en Chile, garantizando la transparencia, integridad, accesibilidad y reproducibilidad en la producción, análsis y difusión de datos sociales**

Con esto, se busca certificar y asegurar: 

- La calidad y transparencia en el diseño de muestras, cuestionarios e hipótesis de investigación.

- El acceso abierto y documentado a microdatos, resguardano la protección y confidencialidad de información sensible. 

- La reproducibilidad de los reportes y análisis derivados de los datos, promoviendo la trazabilidad y el control de versiones en todo el ciclo de investigación. 
